language: python
notifications:
    email:
        on_success: never
        on_failure: always
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
#  - TOXENV=py35
install: "pip install tox"
script: tox
