notifications:
    email:
        on_success: never
        on_failure: always
services:
    - redis-server
language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install .
    - pip install -r requirements.txt
    - pip install python-coveralls
script: py.test
after_success:
    - coveralls
