notifications:
    email:
        on_success: never
        on_failure: always
services:
    - redis-server
language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
install:
    - pip install .
    - pip install -r requirements.txt
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install futures; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then travis_retry pip install futures; fi
    - pip install python-coveralls
script: py.test
after_success:
    - coveralls
